# Generated by Django 3.1.3 on 2020-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLSeason',
            fields=[
                ('season', models.IntegerField(default=2020, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_no', models.AutoField(primary_key=True, serialize=False)),
                ('elected', models.CharField(choices=[('B', 'BAT'), ('F', 'FIELD')], max_length=1)),
                ('first_inning_score', models.IntegerField()),
                ('first_inning_over', models.FloatField()),
                ('second_inning_score', models.IntegerField()),
                ('second_inning_over', models.FloatField()),
            ],
        ),
    ]
