# Generated by Django 3.1.3 on 2020-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20201124_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team_one_txt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_two_txt',
            field=models.CharField(default='', max_length=30),
        ),
    ]
