# Generated by Django 3.1.3 on 2020-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.CharField(default=2020, max_length=10),
        ),
    ]
