# Generated by Django 3.1.3 on 2020-11-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20201124_2129'),
        ('teams', '0002_auto_20201124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.iplseason'),
        ),
    ]
