# Generated by Django 3.1.3 on 2020-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
